import { Roboto } from 'next/font/google';
import Header from '@/components/Header';
import type { Metadata } from 'next';
import './globals.css';

const robotoSans = Roboto({
  variable: '--font-roboto-sans',
  subsets: ['latin'],
  preload: true
});

export const metadata: Metadata = {
  title: 'TG Testing App',
  description: 'Generated by TG devs'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      className="min-h-dvh dark"
      lang="en"
      style={{ colorScheme: 'dark' }}
    >
      <body className={`${robotoSans.variable} flex min-w-full min-h-dvh font-sans antialiased`}>
        <main className="relative grow flex flex-col pt-8 gap-4">
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
