import { Roboto } from 'next/font/google';
import Header from '@/components/Header';
import type { Metadata } from 'next';
import './globals.css';

const robotoSans = Roboto({
  variable: '--font-roboto-sans',
  subsets: ['latin'],
  preload: true,
});

export const metadata: Metadata = {
  title: 'TG Testing App',
  description: 'Generated by TG devs',
};

export const fetchCache = 'force-cache';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      className="min-h-dvh dark"
      lang="en"
      style={{ colorScheme: 'dark' }}
    >
      <body
        className={`${robotoSans.variable} flex w-full min-h-dvh font-sans antialiased overflow-x-hidden`}
      >
        <main className="relative flex flex-col pt-6 px-10 gap-4 w-full">
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
